[package]
default-run = "arcutils"
description = "An executable tool for building rust-based kernels and testing and running them"
edition = "2021"
license = "GPL-3.0-only"
name = "arcutils"
version = "0.1.4"

[dependencies]
const_format = "0.2.23"
